# SPDX-FileCopyrightText: 2026 Malte Dreyer
# SPDX-License-Identifier: MIT
"""initial schema

Revision ID: 5bf309dbdbb8
Revises: 
Create Date: 2026-09-13 19:19:20.098532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5bf309dbdbb8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('display_name_en', sa.String(length=200), nullable=True),
    sa.Column('steckbrief_template', sa.Text(), nullable=False),
    sa.Column('field_groups', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active_groups', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_internal_name'), 'categories', ['internal_name'], unique=True)
    op.create_index(op.f('ix_categories_is_active'), 'categories', ['is_active'], unique=False)
    op.create_table('circuit_breaker_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_name')
    )
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('canonical_name', sa.String(length=500), nullable=False),
    sa.Column('entity_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'canonical_name', name='unique_entity_type_name')
    )
    op.create_index(op.f('ix_entities_canonical_name'), 'entities', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_entities_entity_type'), 'entities', ['entity_type'], unique=False)
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('display_name_en', sa.String(length=200), nullable=True),
    sa.Column('extract_prompt', sa.Text(), nullable=False),
    sa.Column('validate_prompt', sa.Text(), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=True),
    sa.Column('field_group', sa.String(length=50), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('required_confidence', sa.Float(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('translatable', sa.Boolean(), nullable=False),
    sa.Column('translation_context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompts_field_group'), 'prompts', ['field_group'], unique=False)
    op.create_index(op.f('ix_prompts_internal_name'), 'prompts', ['internal_name'], unique=True)
    op.create_index(op.f('ix_prompts_is_active'), 'prompts', ['is_active'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('category_prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'prompt_id', name='unique_category_prompt')
    )
    op.create_index(op.f('ix_category_prompts_category_id'), 'category_prompts', ['category_id'], unique=False)
    op.create_table('entity_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('variant_name', sa.String(length=500), nullable=False),
    sa.Column('is_auto_detected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_variants_entity_id'), 'entity_variants', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_variants_variant_name'), 'entity_variants', ['variant_name'], unique=True)
    op.create_table('prompt_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('depends_on_prompt_id', sa.Integer(), nullable=False),
    sa.Column('context_key', sa.String(length=100), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_id', 'depends_on_prompt_id', name='unique_prompt_dependency')
    )
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=True),
    sa.Column('markdown_size', sa.Integer(), nullable=True),
    sa.Column('pages_crawled', sa.Integer(), nullable=True),
    sa.Column('crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_category_id'), 'sources', ['category_id'], unique=False)
    op.create_index(op.f('ix_sources_status'), 'sources', ['status'], unique=False)
    op.create_index(op.f('ix_sources_url'), 'sources', ['url'], unique=True)
    op.create_table('extractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('raw_result', sa.Text(), nullable=True),
    sa.Column('raw_confidence', sa.Float(), nullable=True),
    sa.Column('extract_duration_ms', sa.Integer(), nullable=True),
    sa.Column('validated_result', sa.Text(), nullable=True),
    sa.Column('validation_quality', sa.String(length=20), nullable=True),
    sa.Column('validation_score', sa.Float(), nullable=True),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.Column('validate_duration_ms', sa.Integer(), nullable=True),
    sa.Column('validated_result_en', sa.Text(), nullable=True),
    sa.Column('translation_status', sa.String(length=20), nullable=True),
    sa.Column('translated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_confidence', sa.Float(), nullable=True),
    sa.Column('is_manual_edit', sa.Boolean(), nullable=False),
    sa.Column('edited_by', sa.String(length=100), nullable=True),
    sa.Column('linked_entity_id', sa.Integer(), nullable=True),
    sa.Column('entity_confidence', sa.Float(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['linked_entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'prompt_id', name='unique_source_prompt_extraction')
    )
    op.create_index(op.f('ix_extractions_final_confidence'), 'extractions', ['final_confidence'], unique=False)
    op.create_index(op.f('ix_extractions_is_manual_edit'), 'extractions', ['is_manual_edit'], unique=False)
    op.create_index(op.f('ix_extractions_linked_entity_id'), 'extractions', ['linked_entity_id'], unique=False)
    op.create_index(op.f('ix_extractions_prompt_id'), 'extractions', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_extractions_source_id'), 'extractions', ['source_id'], unique=False)
    op.create_table('job_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('prompt_id', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_queue_scheduled_at'), 'job_queue', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_job_queue_source_id'), 'job_queue', ['source_id'], unique=False)
    op.create_index(op.f('ix_job_queue_status'), 'job_queue', ['status'], unique=False)
    op.create_table('steckbriefe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    op.create_index(op.f('ix_steckbriefe_published'), 'steckbriefe', ['published'], unique=False)
    op.create_table('entity_normalization_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extraction_id', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('llm_suggestion_id', sa.Integer(), nullable=True),
    sa.Column('llm_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['llm_suggestion_id'], ['entities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_normalization_queue_extraction_id'), 'entity_normalization_queue', ['extraction_id'], unique=False)
    op.create_index(op.f('ix_entity_normalization_queue_status'), 'entity_normalization_queue', ['status'], unique=False)
    op.create_table('steckbrief_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('steckbrief_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('translated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['steckbrief_id'], ['steckbriefe.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('steckbrief_id', 'language', name='unique_steckbrief_language')
    )
    op.create_index(op.f('ix_steckbrief_translations_language'), 'steckbrief_translations', ['language'], unique=False)
    op.create_index(op.f('ix_steckbrief_translations_steckbrief_id'), 'steckbrief_translations', ['steckbrief_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_steckbrief_translations_steckbrief_id'), table_name='steckbrief_translations')
    op.drop_index(op.f('ix_steckbrief_translations_language'), table_name='steckbrief_translations')
    op.drop_table('steckbrief_translations')
    op.drop_index(op.f('ix_entity_normalization_queue_status'), table_name='entity_normalization_queue')
    op.drop_index(op.f('ix_entity_normalization_queue_extraction_id'), table_name='entity_normalization_queue')
    op.drop_table('entity_normalization_queue')
    op.drop_index(op.f('ix_steckbriefe_published'), table_name='steckbriefe')
    op.drop_table('steckbriefe')
    op.drop_index(op.f('ix_job_queue_status'), table_name='job_queue')
    op.drop_index(op.f('ix_job_queue_source_id'), table_name='job_queue')
    op.drop_index(op.f('ix_job_queue_scheduled_at'), table_name='job_queue')
    op.drop_table('job_queue')
    op.drop_index(op.f('ix_extractions_source_id'), table_name='extractions')
    op.drop_index(op.f('ix_extractions_prompt_id'), table_name='extractions')
    op.drop_index(op.f('ix_extractions_linked_entity_id'), table_name='extractions')
    op.drop_index(op.f('ix_extractions_is_manual_edit'), table_name='extractions')
    op.drop_index(op.f('ix_extractions_final_confidence'), table_name='extractions')
    op.drop_table('extractions')
    op.drop_index(op.f('ix_sources_url'), table_name='sources')
    op.drop_index(op.f('ix_sources_status'), table_name='sources')
    op.drop_index(op.f('ix_sources_category_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_table('prompt_dependencies')
    op.drop_index(op.f('ix_entity_variants_variant_name'), table_name='entity_variants')
    op.drop_index(op.f('ix_entity_variants_entity_id'), table_name='entity_variants')
    op.drop_table('entity_variants')
    op.drop_index(op.f('ix_category_prompts_category_id'), table_name='category_prompts')
    op.drop_table('category_prompts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_prompts_is_active'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_internal_name'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_field_group'), table_name='prompts')
    op.drop_table('prompts')
    op.drop_index(op.f('ix_entities_entity_type'), table_name='entities')
    op.drop_index(op.f('ix_entities_canonical_name'), table_name='entities')
    op.drop_table('entities')
    op.drop_table('circuit_breaker_state')
    op.drop_index(op.f('ix_categories_is_active'), table_name='categories')
    op.drop_index(op.f('ix_categories_internal_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
